import './components/dinamicHeight';
import './components/modals';
import './components/select';
import './components/form-validate';
import './components/acc';
import './components/comments';
import './components/post-filter';
import './components/sliders';
import './components/big-calculator';
import './components/mobile-menu';
import './components/tabs';
import './components/calc';
import './components/quiz';
import './components/quiz-settings';
import './components/anchor';
import './components/hiddenText';
import './components/calendar';
// import './components/toTop';
// import './components/post';
// import './components/filters';
// import './components/animations';
// import './components/tabs';
// import './components/ajaxPostTabs';
// import './components/ajaxLoadGallery';
// import './components/barba';
